/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumLightbox: typeof import('./src/components/album/AlbumLightbox.vue')['default']
    AppShell: typeof import('./src/components/layout/AppShell.vue')['default']
    AuroraBackdrop: typeof import('./src/components/Common/AuroraBackdrop.vue')['default']
    ChartWrap: typeof import('./src/components/ChartWrap.vue')['default']
    FestivalEgg: typeof import('./src/components/Common/FestivalEgg.vue')['default']
    FloatingHearts: typeof import('./src/components/Common/FloatingHearts.vue')['default']
    GradientText: typeof import('./src/components/Common/GradientText.vue')['default']
    HeartBurstLayer: typeof import('./src/components/Common/HeartBurstLayer.vue')['default']
    HeroIcon: typeof import('./src/components/Common/HeroIcon.vue')['default']
    ImageField: typeof import('./src/components/Common/ImageField.vue')['default']
    IndButton: typeof import('./src/components/industrial/IndButton.vue')['default']
    IndCard: typeof import('./src/components/industrial/IndCard.vue')['default']
    IndEmpty: typeof import('./src/components/industrial/IndEmpty.vue')['default']
    IndLed: typeof import('./src/components/industrial/IndLed.vue')['default']
    IndPager: typeof import('./src/components/industrial/IndPager.vue')['default']
    IndProgressRing: typeof import('./src/components/industrial/IndProgressRing.vue')['default']
    IndSectionTitle: typeof import('./src/components/industrial/IndSectionTitle.vue')['default']
    IndSkeleton: typeof import('./src/components/industrial/IndSkeleton.vue')['default']
    IndStatCard: typeof import('./src/components/industrial/IndStatCard.vue')['default']
    LoveCount: typeof import('./src/components/Common/LoveCount.vue')['default']
    MilestoneStrip: typeof import('./src/components/Common/MilestoneStrip.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    Onboarding: typeof import('./src/components/Onboarding.vue')['default']
    PageTransition: typeof import('./src/components/Common/PageTransition.vue')['default']
    PartnerActivityToast: typeof import('./src/components/Common/PartnerActivityToast.vue')['default']
    PullRefresh: typeof import('./src/components/Common/PullRefresh.vue')['default']
    RouteProgress: typeof import('./src/components/Common/RouteProgress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
  }
}
